# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiLib/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 735)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 90, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.SpectrumLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.SpectrumLayout.setContentsMargins(0, 0, 0, 0)
        self.SpectrumLayout.setObjectName("SpectrumLayout")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(280, 130, 2, 2))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.SpectrumLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.SpectrumLayout_2.setContentsMargins(0, 0, 0, 0)
        self.SpectrumLayout_2.setObjectName("SpectrumLayout_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(280, 130, 2, 2))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.SpectrumLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.SpectrumLayout_3.setContentsMargins(0, 0, 0, 0)
        self.SpectrumLayout_3.setObjectName("SpectrumLayout_3")
        self.tabWidget.addTab(self.widget, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.FrfWidget = MplWidget(self.widget1)
        self.FrfWidget.setObjectName("FrfWidget")
        self.gridLayout_2.addWidget(self.FrfWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.widget1, "")
        self.widget2 = QtWidgets.QWidget()
        self.widget2.setObjectName("widget2")
        self.tabWidget.addTab(self.widget2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_AboutAuthor = QtWidgets.QAction(MainWindow)
        self.action_AboutAuthor.setObjectName("action_AboutAuthor")
        self.action_AboutSystem = QtWidgets.QAction(MainWindow)
        self.action_AboutSystem.setObjectName("action_AboutSystem")
        self.action_SignalSample = QtWidgets.QAction(MainWindow)
        self.action_SignalSample.setObjectName("action_SignalSample")
        self.action_SignalGen = QtWidgets.QAction(MainWindow)
        self.action_SignalGen.setObjectName("action_SignalGen")
        self.actionModel_Design = QtWidgets.QAction(MainWindow)
        self.actionModel_Design.setObjectName("actionModel_Design")
        self.menuFile.addAction(self.action_SignalSample)
        self.menuFile.addAction(self.action_SignalGen)
        self.menuSetting.addAction(self.actionModel_Design)
        self.menuAbout.addAction(self.action_AboutAuthor)
        self.menuAbout.addAction(self.action_AboutSystem)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "模态几何"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget1), _translate("MainWindow", "输入输出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget2), _translate("MainWindow", "模态分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "3D显示"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.action_AboutAuthor.setText(_translate("MainWindow", "About Author"))
        self.action_AboutSystem.setText(_translate("MainWindow", "About System"))
        self.action_SignalSample.setText(_translate("MainWindow", "Signal Sampling"))
        self.action_SignalGen.setText(_translate("MainWindow", "Signal Generation"))
        self.actionModel_Design.setText(_translate("MainWindow", "Model Design"))

from MplWidget import MplWidget
