# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiLib/SignalSample.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SignalSampleDialog(object):
    def setupUi(self, SignalSampleDialog):
        SignalSampleDialog.setObjectName("SignalSampleDialog")
        SignalSampleDialog.resize(626, 490)
        self.gridLayout_2 = QtWidgets.QGridLayout(SignalSampleDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_Response = QtWidgets.QTabWidget(SignalSampleDialog)
        self.tabWidget_Response.setObjectName("tabWidget_Response")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.widget = MplWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 2)
        self.tabWidget_Response.addTab(self.tab, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Stimulate = QtWidgets.QLabel(self.widget1)
        self.label_Stimulate.setObjectName("label_Stimulate")
        self.verticalLayout.addWidget(self.label_Stimulate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_Stimulate = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_Stimulate.setObjectName("lineEdit_Stimulate")
        self.horizontalLayout_2.addWidget(self.lineEdit_Stimulate)
        self.pushButton_OpenStimulate = QtWidgets.QPushButton(self.widget1)
        self.pushButton_OpenStimulate.setObjectName("pushButton_OpenStimulate")
        self.horizontalLayout_2.addWidget(self.pushButton_OpenStimulate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget_Stimulate = QtWidgets.QListWidget(self.widget1)
        self.listWidget_Stimulate.setObjectName("listWidget_Stimulate")
        self.horizontalLayout.addWidget(self.listWidget_Stimulate)
        self.MplWidget_Stimulate = MplWidget(self.widget1)
        self.MplWidget_Stimulate.setObjectName("MplWidget_Stimulate")
        self.horizontalLayout.addWidget(self.MplWidget_Stimulate)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 12)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget_Response.addTab(self.widget1, "")
        self.widget2 = QtWidgets.QWidget()
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Response = QtWidgets.QLabel(self.widget2)
        self.label_Response.setObjectName("label_Response")
        self.verticalLayout_3.addWidget(self.label_Response)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_Response = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_Response.setObjectName("lineEdit_Response")
        self.horizontalLayout_5.addWidget(self.lineEdit_Response)
        self.pushButton_OpenResponse = QtWidgets.QPushButton(self.widget2)
        self.pushButton_OpenResponse.setObjectName("pushButton_OpenResponse")
        self.horizontalLayout_5.addWidget(self.pushButton_OpenResponse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listWidget_Response = QtWidgets.QListWidget(self.widget2)
        self.listWidget_Response.setObjectName("listWidget_Response")
        self.horizontalLayout_6.addWidget(self.listWidget_Response)
        self.MplWidget_Response = MplWidget(self.widget2)
        self.MplWidget_Response.setObjectName("MplWidget_Response")
        self.horizontalLayout_6.addWidget(self.MplWidget_Response)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget_Response.addTab(self.widget2, "")
        self.gridLayout_2.addWidget(self.tabWidget_Response, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_Domain = QtWidgets.QComboBox(SignalSampleDialog)
        self.comboBox_Domain.setObjectName("comboBox_Domain")
        self.comboBox_Domain.addItem("")
        self.comboBox_Domain.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_Domain)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(SignalSampleDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_7.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)

        self.retranslateUi(SignalSampleDialog)
        self.tabWidget_Response.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SignalSampleDialog.accept)
        self.buttonBox.rejected.connect(SignalSampleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SignalSampleDialog)

    def retranslateUi(self, SignalSampleDialog):
        _translate = QtCore.QCoreApplication.translate
        SignalSampleDialog.setWindowTitle(_translate("SignalSampleDialog", "Signal Sample"))
        self.pushButton.setText(_translate("SignalSampleDialog", "Open Device"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.tab), _translate("SignalSampleDialog", "Real Time Sample"))
        self.label_Stimulate.setText(_translate("SignalSampleDialog", "Stimulate Signal"))
        self.pushButton_OpenStimulate.setText(_translate("SignalSampleDialog", "Open File"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.widget1), _translate("SignalSampleDialog", "Import Stimulate"))
        self.label_Response.setText(_translate("SignalSampleDialog", "Response Signal"))
        self.pushButton_OpenResponse.setText(_translate("SignalSampleDialog", "Open File"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.widget2), _translate("SignalSampleDialog", "Import Response"))
        self.comboBox_Domain.setItemText(0, _translate("SignalSampleDialog", "时域"))
        self.comboBox_Domain.setItemText(1, _translate("SignalSampleDialog", "频域"))

from mplwidget import MplWidget
