# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiLib/SignalSample.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignalSampleDialog(object):
    def setupUi(self, SignalSampleDialog):
        SignalSampleDialog.setObjectName("SignalSampleDialog")
        SignalSampleDialog.resize(737, 594)
        self.gridLayout_2 = QtWidgets.QGridLayout(SignalSampleDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_Domain = QtWidgets.QComboBox(SignalSampleDialog)
        self.comboBox_Domain.setObjectName("comboBox_Domain")
        self.comboBox_Domain.addItem("")
        self.comboBox_Domain.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_Domain)
        self.label = QtWidgets.QLabel(SignalSampleDialog)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.doubleSpinBox_UpperFrequence = QtWidgets.QDoubleSpinBox(SignalSampleDialog)
        self.doubleSpinBox_UpperFrequence.setEnabled(True)
        self.doubleSpinBox_UpperFrequence.setMaximum(1500.0)
        self.doubleSpinBox_UpperFrequence.setSingleStep(100.0)
        self.doubleSpinBox_UpperFrequence.setProperty("value", 1200.0)
        self.doubleSpinBox_UpperFrequence.setObjectName("doubleSpinBox_UpperFrequence")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_UpperFrequence)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(SignalSampleDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_7.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabWidget_Response = QtWidgets.QTabWidget(SignalSampleDialog)
        self.tabWidget_Response.setObjectName("tabWidget_Response")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.widget = MplWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 2)
        self.tabWidget_Response.addTab(self.tab, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Stimulate = QtWidgets.QLabel(self.widget1)
        self.label_Stimulate.setObjectName("label_Stimulate")
        self.verticalLayout.addWidget(self.label_Stimulate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_Stimulate = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_Stimulate.setObjectName("lineEdit_Stimulate")
        self.horizontalLayout_2.addWidget(self.lineEdit_Stimulate)
        self.pushButton_OpenStimulate = QtWidgets.QPushButton(self.widget1)
        self.pushButton_OpenStimulate.setObjectName("pushButton_OpenStimulate")
        self.horizontalLayout_2.addWidget(self.pushButton_OpenStimulate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget_Stimulate = QtWidgets.QListWidget(self.widget1)
        self.listWidget_Stimulate.setObjectName("listWidget_Stimulate")
        self.horizontalLayout.addWidget(self.listWidget_Stimulate)
        self.MplWidget_Stimulate = MplWidget(self.widget1)
        self.MplWidget_Stimulate.setObjectName("MplWidget_Stimulate")
        self.horizontalLayout.addWidget(self.MplWidget_Stimulate)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 12)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget_Response.addTab(self.widget1, "")
        self.widget2 = QtWidgets.QWidget()
        self.widget2.setObjectName("widget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Response = QtWidgets.QLabel(self.widget2)
        self.label_Response.setObjectName("label_Response")
        self.horizontalLayout_3.addWidget(self.label_Response)
        spacerItem1 = QtWidgets.QSpacerItem(193, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.widget2)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_Response = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_Response.setObjectName("lineEdit_Response")
        self.horizontalLayout_5.addWidget(self.lineEdit_Response)
        self.pushButton_OpenResponse = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_OpenResponse.setObjectName("pushButton_OpenResponse")
        self.horizontalLayout_5.addWidget(self.pushButton_OpenResponse)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listWidget_Response = QtWidgets.QListWidget(self.tab_3)
        self.listWidget_Response.setObjectName("listWidget_Response")
        self.horizontalLayout_6.addWidget(self.listWidget_Response)
        self.MplWidget_Response = MplWidget(self.tab_3)
        self.MplWidget_Response.setObjectName("MplWidget_Response")
        self.horizontalLayout_6.addWidget(self.MplWidget_Response)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_Response_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_Response_2.setObjectName("lineEdit_Response_2")
        self.horizontalLayout_9.addWidget(self.lineEdit_Response_2)
        self.pushButton_OpenResponse_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_OpenResponse_2.setObjectName("pushButton_OpenResponse_2")
        self.horizontalLayout_9.addWidget(self.pushButton_OpenResponse_2)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listWidget_Response_2 = QtWidgets.QListWidget(self.tab_4)
        self.listWidget_Response_2.setObjectName("listWidget_Response_2")
        self.horizontalLayout_8.addWidget(self.listWidget_Response_2)
        self.MplWidget_Response_2 = MplWidget(self.tab_4)
        self.MplWidget_Response_2.setObjectName("MplWidget_Response_2")
        self.horizontalLayout_8.addWidget(self.MplWidget_Response_2)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 12)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.tabWidget_Response.addTab(self.widget2, "")
        self.gridLayout_2.addWidget(self.tabWidget_Response, 0, 0, 1, 1)

        self.retranslateUi(SignalSampleDialog)
        self.tabWidget_Response.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SignalSampleDialog.accept)
        self.buttonBox.rejected.connect(SignalSampleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SignalSampleDialog)

    def retranslateUi(self, SignalSampleDialog):
        _translate = QtCore.QCoreApplication.translate
        SignalSampleDialog.setWindowTitle(_translate("SignalSampleDialog", "Signal Sample"))
        self.comboBox_Domain.setItemText(0, _translate("SignalSampleDialog", "时域"))
        self.comboBox_Domain.setItemText(1, _translate("SignalSampleDialog", "频域"))
        self.label.setText(_translate("SignalSampleDialog", "截止频率"))
        self.pushButton.setText(_translate("SignalSampleDialog", "Open Device"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.tab), _translate("SignalSampleDialog", "Real Time Sample"))
        self.label_Stimulate.setText(_translate("SignalSampleDialog", "Stimulate Signal"))
        self.pushButton_OpenStimulate.setText(_translate("SignalSampleDialog", "Open File"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.widget1), _translate("SignalSampleDialog", "Import Stimulate"))
        self.label_Response.setText(_translate("SignalSampleDialog", "Response Signal"))
        self.pushButton_2.setText(_translate("SignalSampleDialog", "Add Channel"))
        self.pushButton_OpenResponse.setText(_translate("SignalSampleDialog", "Open File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SignalSampleDialog", "Channel 1"))
        self.pushButton_OpenResponse_2.setText(_translate("SignalSampleDialog", "Open File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("SignalSampleDialog", "Channel 2"))
        self.tabWidget_Response.setTabText(self.tabWidget_Response.indexOf(self.widget2), _translate("SignalSampleDialog", "Import Response"))
from MplWidget import MplWidget
